# Generated by Django 2.0.6 on 2018-07-21 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('identification_card', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lastName', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('answer1', models.CharField(max_length=120)),
                ('answer2', models.CharField(max_length=120)),
                ('answer3', models.CharField(max_length=120)),
                ('birthdate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
